countries =[
    ("AF", "Afghanistan", "Afghanistan - أفغانستان"),
    ("AL", "Albania", "Albania - ألبانيا"),
    ("DZ", "Algeria", "Algeria - الجزائر"),
    ("AS", "American Samoa", "American Samoa - ساموا الأمريكية"),
    ("AD", "Andorra", "Andorra - أندورا"),
    ("AO", "Angola", "Angola - أنغولا"),
    ("AI", "Anguilla", "Anguilla - أنغويلا"),
    ("AQ", "Antarctica", "Antarctica - القارة القطبية الجنوبية"),
    ("AG", "Antigua and Barbuda", "Antigua and Barbuda - أنتيغوا وبربودا"),
    ("AR", "Argentina", "Argentina - الأرجنتين"),
    ("AM", "Armenia", "Armenia - أرمينيا"),
    ("AW", "Aruba", "Aruba - أروبا"),
    ("AU", "Australia", "Australia - أستراليا"),
    ("AT", "Austria", "Austria - النمسا"),
    ("AZ", "Azerbaijan", "Azerbaijan - أذربيجان"),
    ("BS", "Bahamas", "Bahamas - جزر البهاما"),
    ("BH", "Bahrain", "Bahrain - البحرين"),
    ("BD", "Bangladesh", "Bangladesh - بنغلاديش"),
    ("BB", "Barbados", "Barbados - بربادوس"),
    ("BY", "Belarus", "Belarus - روسيا البيضاء"),
    ("BE", "Belgium", "Belgium - بلجيكا"),
    ("BZ", "Belize", "Belize - بليز"),
    ("BJ", "Benin", "Benin - بنين"),
    ("BM", "Bermuda", "Bermuda - برمودا"),
    ("BT", "Bhutan", "Bhutan - بوتان"),
    ("BO", "Bolivia", "Bolivia - بوليفيا"),
    ("BA", "Bosnia and Herzegovina", "Bosnia and Herzegovina - البوسنة والهرسك"),
    ("BW", "Botswana", "Botswana - بوتسوانا"),
    ("BV", "Bouvet Island", "Bouvet Island - جزيرة بوفيه"),
    ("BR", "Brazil", "Brazil - البرازيل"),
    ("IO", "British Indian Ocean Territory", "British Indian Ocean Territory - إقليم المحيط الهندي البريطاني"),
    ("VG", "British Virgin Islands", "British Virgin Islands - جزر فيرجن البريطانية"),
    ("BN", "Brunei", "Brunei - بروناي"),
    ("BG", "Bulgaria", "Bulgaria - بلغاريا"),
    ("BF", "Burkina Faso", "Burkina Faso - بوركينا فاسو"),
    ("BI", "Burundi", "Burundi - بوروندي"),
    ("KH", "Cambodia", "Cambodia - كمبوديا"),
    ("CM", "Cameroon", "Cameroon - الكاميرون"),
    ("CA", "Canada", "Canada - كندا"),
    ("CV", "Cape Verde", "Cape Verde - الرأس الأخضر"),
    ("BQ", "Caribbean Netherlands", "Caribbean Netherlands - الكاريبي الهولندي"),
    ("KY", "Cayman Islands", "Cayman Islands - جزر كايمان"),
    ("CF", "Central African Republic", "Central African Republic - جمهورية أفريقيا الوسطى"),
    ("TD", "Chad", "Chad - تشاد"),
    ("CL", "Chile", "Chile - تشيلي"),
    ("CN", "China", "China - الصين"),
    ("CX", "Christmas Island", "Christmas Island - جزيرة الكريسماس"),
    ("CC", "Cocos (Keeling) Islands", "Cocos (Keeling) Islands - جزر كوكوس (كيلينغ)"),
    ("CO", "Colombia", "Colombia - كولومبيا"),
    ("KM", "Comoros", "Comoros - جزر القمر"),
    ("CG", "Congo - Brazzaville", "Congo - Brazzaville - الكونغو - برازافيل"),
    ("CD", "Congo - Kinshasa", "Congo - Kinshasa - الكونغو - كينشاسا"),
    ("CK", "Cook Islands", "Cook Islands - جزر كوك"),
    ("CR", "Costa Rica", "Costa Rica - كوستاريكا"),
    ("CI", "Côte d’Ivoire", "Côte d’Ivoire - ساحل العاج"),
    ("HR", "Croatia", "Croatia - كرواتيا"),
    ("CU", "Cuba", "Cuba - كوبا"),
    ("CW", "Curaçao", "Curaçao - كوراساو"),
    ("CY", "Cyprus", "Cyprus - قبرص"),
    ("CZ", "Czechia", "Czechia - التشيك"),
    ("DK", "Denmark", "Denmark - الدنمارك"),
    ("DJ", "Djibouti", "Djibouti - جيبوتي"),
    ("DM", "Dominica", "Dominica - دومينيكا"),
    ("DO", "Dominican Republic", "Dominican Republic - جمهورية الدومينيكان"),
    ("EC", "Ecuador", "Ecuador - الإكوادور"),
    ("EG", "Egypt", "Egypt - مصر"),
    ("SV", "El Salvador", "El Salvador - السلفادور"),
    ("GQ", "Equatorial Guinea", "Equatorial Guinea - غينيا الاستوائية"),
    ("ER", "Eritrea", "Eritrea - إريتريا"),
    ("EE", "Estonia", "Estonia - إستونيا"),
    ("SZ", "Eswatini", "Eswatini - إسواتيني"),
    ("ET", "Ethiopia", "Ethiopia - إثيوبيا"),
    ("FK", "Falkland Islands", "Falkland Islands - جزر فوكلاند"),
    ("FO", "Faroe Islands", "Faroe Islands - جزر فارو"),
    ("FJ", "Fiji", "Fiji - فيجي"),
    ("FI", "Finland", "Finland - فنلندا"),
    ("FR", "France", "France - فرنسا"),
    ("GF", "French Guiana", "French Guiana - غويانا الفرنسية"),
    ("PF", "French Polynesia", "French Polynesia - بولينيزيا الفرنسية"),
    ("TF", "French Southern Territories", "French Southern Territories - الأقاليم الجنوبية الفرنسية"),
    ("GA", "Gabon", "Gabon - الغابون"),
    ("GM", "Gambia", "Gambia - غامبيا"),
    ("GE", "Georgia", "Georgia - جورجيا"),
    ("DE", "Germany", "Germany - ألمانيا"),
    ("GH", "Ghana", "Ghana - غانا"),
    ("GI", "Gibraltar", "Gibraltar - جبل طارق"),
    ("GR", "Greece", "Greece - اليونان"),
    ("GL", "Greenland", "Greenland - جرينلاند"),
    ("GD", "Grenada", "Grenada - غرينادا"),
    ("GP", "Guadeloupe", "Guadeloupe - جوادلوب"),
    ("GU", "Guam", "Guam - غوام"),
    ("GT", "Guatemala", "Guatemala - غواتيمالا"),
    ("GG", "Guernsey", "Guernsey - غيرنزي"),
    ("GN", "Guinea", "Guinea - غينيا"),
    ("GW", "Guinea-Bissau", "Guinea-Bissau - غينيا بيساو"),
    ("GY", "Guyana", "Guyana - غيانا"),
    ("HT", "Haiti", "Haiti - هايتي"),
    ("HM", "Heard & McDonald Islands", "Heard & McDonald Islands - جزر هيرد وماكدونالد"),
    ("HN", "Honduras", "Honduras - هندوراس"),
    ("HK", "Hong Kong SAR China", "Hong Kong SAR China - هونغ كونغ"),
    ("HU", "Hungary", "Hungary - المجر"),
    ("IS", "Iceland", "Iceland - آيسلندا"),
    ("IN", "India", "India - الهند"),
    ("ID", "Indonesia", "Indonesia - إندونيسيا"),
    ("IR", "Iran", "Iran - إيران"),
    ("IQ", "Iraq", "Iraq - العراق"),
    ("IE", "Ireland", "Ireland - أيرلندا"),
    ("IM", "Isle of Man", "Isle of Man - جزيرة مان"),
    ("IL", "Israel", "Israel - إسرائيل"),
    ("IT", "Italy", "Italy - إيطاليا"),
    ("JM", "Jamaica", "Jamaica - جامايكا"),
    ("JP", "Japan", "Japan - اليابان"),
    ("JE", "Jersey", "Jersey - جيرزي"),
    ("JO", "Jordan", "Jordan - الأردن"),
    ("KZ", "Kazakhstan", "Kazakhstan - كازاخستان"),
    ("KE", "Kenya", "Kenya - كينيا"),
    ("KI", "Kiribati", "Kiribati - كيريباتي"),
    ("XK", "Kosovo", "Kosovo - كوسوفو"),
    ("KW", "Kuwait", "Kuwait - الكويت"),
    ("KG", "Kyrgyzstan", "Kyrgyzstan - قيرغيزستان"),
    ("LA", "Laos", "Laos - لاوس"),
    ("LV", "Latvia", "Latvia - لاتفيا"),
    ("LB", "Lebanon", "Lebanon - لبنان"),
    ("LS", "Lesotho", "Lesotho - ليسوتو"),
    ("LR", "Liberia", "Liberia - ليبيريا"),
    ("LY", "Libya", "Libya - ليبيا"),
    ("LI", "Liechtenstein", "Liechtenstein - ليختنشتاين"),
    ("LT", "Lithuania", "Lithuania - ليتوانيا"),
    ("LU", "Luxembourg", "Luxembourg - لوكسمبورغ"),
    ("MO", "Macao SAR China", "Macao SAR China - ماكاو"),
    ("MG", "Madagascar", "Madagascar - مدغشقر"),
    ("MW", "Malawi", "Malawi - مالاوي"),
    ("MY", "Malaysia", "Malaysia - ماليزيا"),
    ("MV", "Maldives", "Maldives - المالديف"),
    ("ML", "Mali", "Mali - مالي"),
    ("MT", "Malta", "Malta - مالطا"),
    ("MH", "Marshall Islands", "Marshall Islands - جزر مارشال"),
    ("MQ", "Martinique", "Martinique - مارتينيك"),
    ("MR", "Mauritania", "Mauritania - موريتانيا"),
    ("MU", "Mauritius", "Mauritius - موريشيوس"),
    ("YT", "Mayotte", "Mayotte - مايوت"),
    ("MX", "Mexico", "Mexico - المكسيك"),
    ("FM", "Micronesia", "Micronesia - ميكرونيزيا"),
    ("MD", "Moldova", "Moldova - مولدوفا"),
    ("MC", "Monaco", "Monaco - موناكو"),
    ("MN", "Mongolia", "Mongolia - منغوليا"),
    ("ME", "Montenegro", "Montenegro - الجبل الأسود"),
    ("MS", "Montserrat", "Montserrat - مونتسيرات"),
    ("MA", "Morocco", "Morocco - المغرب"),
    ("MZ", "Mozambique", "Mozambique - موزمبيق"),
    ("MM", "Myanmar (Burma)", "Myanmar (Burma) - ميانمار"),
    ("NA", "Namibia", "Namibia - ناميبيا"),
    ("NR", "Nauru", "Nauru - ناورو"),
    ("NP", "Nepal", "Nepal - نيبال"),
    ("NL", "Netherlands", "Netherlands - هولندا"),
    ("NC", "New Caledonia", "New Caledonia - كاليدونيا الجديدة"),
    ("NZ", "New Zealand", "New Zealand - نيوزيلندا"),
    ("NI", "Nicaragua", "Nicaragua - نيكاراغوا"),
    ("NE", "Niger", "Niger - النيجر"),
    ("NG", "Nigeria", "Nigeria - نيجيريا"),
    ("NU", "Niue", "Niue - نيوي"),
    ("NF", "Norfolk Island", "Norfolk Island - جزيرة نورفولك"),
    ("KP", "North Korea", "North Korea - كوريا الشمالية"),
    ("MK", "North Macedonia", "North Macedonia - مقدونيا الشمالية"),
    ("MP", "Northern Mariana Islands", "Northern Mariana Islands - جزر ماريانا الشمالية"),
    ("NO", "Norway", "Norway - النرويج"),
    ("OM", "Oman", "Oman - عمان"),
    ("PK", "Pakistan", "Pakistan - باكستان"),
    ("PW", "Palau", "Palau - بالاو"),
    ("PS", "Palestinian Territories", "Palestinian Territories - الأراضي الفلسطينية"),
    ("PA", "Panama", "Panama - بنما"),
    ("PG", "Papua New Guinea", "Papua New Guinea - بابوا غينيا الجديدة"),
    ("PY", "Paraguay", "Paraguay - باراغواي"),
    ("PE", "Peru", "Peru - بيرو"),
    ("PH", "Philippines", "Philippines - الفلبين"),
    ("PN", "Pitcairn Islands", "Pitcairn Islands - جزر بيتكيرن"),
    ("PL", "Poland", "Poland - بولندا"),
    ("PT", "Portugal", "Portugal - البرتغال"),
    ("PR", "Puerto Rico", "Puerto Rico - بورتو ريكو"),
    ("QA", "Qatar", "Qatar - قطر"),
    ("RE", "Réunion", "Réunion - ريونيون"),
    ("RO", "Romania", "Romania - رومانيا"),
    ("RU", "Russia", "Russia - روسيا"),
    ("RW", "Rwanda", "Rwanda - رواندا"),
    ("WS", "Samoa", "Samoa - ساموا"),
    ("SM", "San Marino", "San Marino - سان مارينو"),
    ("ST", "São Tomé & Príncipe", "São Tomé & Príncipe - ساو تومي وبرينسيبي"),
    ("SA", "Saudi Arabia", "Saudi Arabia - السعودية"),
    ("SN", "Senegal", "Senegal - السنغال"),
    ("RS", "Serbia", "Serbia - صربيا"),
    ("SC", "Seychelles", "Seychelles - سيشل"),
    ("SL", "Sierra Leone", "Sierra Leone - سيراليون"),
    ("SG", "Singapore", "Singapore - سنغافورة"),
    ("SX", "Sint Maarten", "Sint Maarten - سينت مارتن"),
    ("SK", "Slovakia", "Slovakia - سلوفاكيا"),
    ("SI", "Slovenia", "Slovenia - سلوفينيا"),
    ("SB", "Solomon Islands", "Solomon Islands - جزر سليمان"),
    ("SO", "Somalia", "Somalia - الصومال"),
    ("ZA", "South Africa", "South Africa - جنوب أفريقيا"),
    ("GS", "South Georgia & South Sandwich Islands", "South Georgia & South Sandwich Islands - جزر جورجيا الجنوبية وساندويتش الجنوبية"),
    ("KR", "South Korea", "South Korea - كوريا الجنوبية"),
    ("SS", "South Sudan", "South Sudan - جنوب السودان"),
    ("ES", "Spain", "Spain - إسبانيا"),
    ("LK", "Sri Lanka", "Sri Lanka - سريلانكا"),
    ("BL", "St. Barthélemy", "St. Barthélemy - سان بارتيلمي"),
    ("SH", "St. Helena", "St. Helena - سانت هيلينا"),
    ("KN", "St. Kitts & Nevis", "St. Kitts & Nevis - سانت كيتس ونيفيس"),
    ("LC", "St. Lucia", "St. Lucia - سانت لوسيا"),
    ("MF", "St. Martin", "St. Martin - سانت مارتن"),
    ("PM", "St. Pierre & Miquelon", "St. Pierre & Miquelon - سان بيير وميكلون"),
    ("VC", "St. Vincent & Grenadines", "St. Vincent & Grenadines - سانت فينسنت وجزر غرينادين"),
    ("SD", "Sudan", "Sudan - السودان"),
    ("SR", "Suriname", "Suriname - سورينام"),
    ("SJ", "Svalbard & Jan Mayen", "Svalbard & Jan Mayen - سفالبارد ويان ماين"),
    ("SE", "Sweden", "Sweden - السويد"),
    ("CH", "Switzerland", "Switzerland - سويسرا"),
    ("SY", "Syria", "Syria - سوريا"),
    ("TW", "Taiwan", "Taiwan - تايوان"),
    ("TJ", "Tajikistan", "Tajikistan - طاجيكستان"),
    ("TZ", "Tanzania", "Tanzania - تنزانيا"),
    ("TH", "Thailand", "Thailand - تايلاند"),
    ("TL", "Timor-Leste", "Timor-Leste - تيمور الشرقية"),
    ("TG", "Togo", "Togo - توغو"),
    ("TK", "Tokelau", "Tokelau - توكيلاو"),
    ("TO", "Tonga", "Tonga - تونغا"),
    ("TT", "Trinidad & Tobago", "Trinidad & Tobago - ترينيداد وتوباغو"),
    ("TN", "Tunisia", "Tunisia - تونس"),
    ("TR", "Turkey", "Turkey - تركيا"),
    ("TM", "Turkmenistan", "Turkmenistan - تركمانستان"),
    ("TC", "Turks & Caicos Islands", "Turks & Caicos Islands - جزر تركس وكايكوس"),
    ("TV", "Tuvalu", "Tuvalu - توفالو"),
    ("UG", "Uganda", "Uganda - أوغندا"),
    ("UA", "Ukraine", "Ukraine - أوكرانيا"),
    ("AE", "United Arab Emirates", "United Arab Emirates - الإمارات"),
    ("GB", "United Kingdom", "United Kingdom - المملكة المتحدة"),
    ("US", "United States", "United States - الولايات المتحدة"),
    ("UY", "Uruguay", "Uruguay - الأوروغواي"),
    ("UZ", "Uzbekistan", "Uzbekistan - أوزبكستان"),
    ("VU", "Vanuatu", "Vanuatu - فانواتو"),
    ("VA", "Vatican City", "Vatican City - الفاتيكان"),
    ("VE", "Venezuela", "Venezuela - فنزويلا"),
    ("VN", "Vietnam", "Vietnam - فيتنام"),
    ("WF", "Wallis & Futuna", "Wallis & Futuna - واليس وفوتونا"),
    ("YE", "Yemen", "Yemen - اليمن"),
    ("ZM", "Zambia", "Zambia - زامبيا"),
    ("ZW", "Zimbabwe", "Zimbabwe - زيمبابوي"),
]