# Generated by Django 5.2.8 on 2026-01-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writerprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FOUNDER', 'مؤسس'), ('HIGH_ADMIN', 'ادمن عالي'), ('REGULAR', 'عادي'), ('READER', 'حساب قاري'), ('WRITER', 'حساب كاتب'), ('MUAASIS', 'المؤسس'), ('EDU_CENTER', 'المركز التعليمي'), ('TEACHER', 'معلم'), ('STUDENT', 'طالب'), ('GUEST', 'زائر')], default='REGULAR', max_length=20),
        ),
        migrations.DeleteModel(
            name='EduCenter',
        ),
        migrations.DeleteModel(
            name='WriterProfile',
        ),
    ]
