# Generated by Django 6.0.3 on 2026-03-22 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FOUNDER', 'مؤسس'), ('HIGH_ADMIN', 'ادمن عالي'), ('REGULAR', 'عادي'), ('READER', 'حساب قاري'), ('WRITER', 'حساب كاتب'), ('MUAASIS', 'المؤسس'), ('EDU_CENTER', 'المركز التعليمي'), ('EDU_CENTER_TEACHER', 'معلم في مركز تعليمي'), ('EDU_CENTER_STUDENT', 'طالب في مركز تعليمي'), ('GUEST', 'زائر')], default='REGULAR', max_length=20),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'شهري'), ('YEARLY', 'سنوي'), ('EDUCATIONAL', 'تعليمي')], default='MONTHLY', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('EXPIRED', 'منتهي'), ('CANCELLED', 'ملغى'), ('PENDING', 'معلق')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('educational_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
