"""
This type stub file was generated by pyright.
"""

from babel import support
from flask import current_app, request
from flask_babel import get_locale
from wtforms.i18n import messages_path

__all__ = ("Translations", "translations")
class Translations:
    def gettext(self, string): # -> str | Any:
        ...
    
    def ngettext(self, singular, plural, n): # -> str | Any:
        ...
    


translations = ...
