# Generated by Django 6.0.3 on 2026-03-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='file_path',
            field=models.FileField(upload_to='stories/%Y/%m/%d/'),
        ),
    ]
